### ISSUE TITLE
Error founded in "Move Eye" tutorial

### ISSUE THREAD

**Issue by ambruslucas** [processing/processing-examples#5] opened 2022-02-20 00:02 UTC
This is the link: https://processing.org/examples/moveeye.html
Just add the following lines in the beginning of the code:
```
void settings() {
  System.setProperty("jogl.disable.openglcore", "true");
  size(640, 360, P3D);
}
```
In the void setup you must remove the size parameters because its already 
declared in void settings.

**Comment by SableRaf** [comment] 2022-08-24 08:57
Hi @ambruslucas and thanks for your suggestion. In Processing the `size()` function is called in `setup()` to define the dimensions of the sketch window. There is no need for an extra `settings()` function. The MoveEye example works as intended. Closing this issue.

**Closed by SableRaf** 2022-08-24 08:57 UTC
